const app=()=>getApp()
Page({
 data:{role:'customer',lang:'zh',tab:'wishlist',tabs:[],rows:[],modal:'',form:{},order:null,addresses:[],detail:null},
 async onShow(){const role=app().globalData.role;const tabs=role==='merchant'?[{key:'quotes',name:'我的报价 / Offers'},{key:'catalog',name:'我的商品 / Products'}]:[{key:'wishlist',name:'选购清单 / Lists'},{key:'inquiries',name:'询价 / Inquiries'},{key:'orders',name:'订单 / Orders'},{key:'tickets',name:'售后 / Service'}];this.setData({role,lang:app().globalData.lang,tabs,tab:tabs.some(x=>x.key===this.data.tab)?this.data.tab:tabs[0].key});if(app().requireLogin())await this.load()},
 async load(){const route=this.data.tab==='catalog'?'/admin/catalog':'/'+this.data.tab;let rows=await app().request(route);rows=rows.filter(Boolean).map(x=>({...x,priceText:app().money(x.total??x.price??x.sku?.price),picture:x.sku?app().picture(x.sku.images[0]):x.skus?app().picture(x.skus[0].images[0]):'',summary:x.items?x.items.map(i=>'SKU '+i.sku_id+' × '+i.quantity).join(' / '):''}));this.setData({rows})},
 async tab(e){this.setData({tab:e.currentTarget.dataset.key});await this.load()},
 input(e){this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value})},
 selectAddress(e){const index=Number(e.detail.value);this.setData({'form.address_id':this.data.addresses[index].id,'form.address_label':this.data.addresses[index].detail})},
 delivery(e){this.setData({'form.delivery_mode':e.detail.value?'delivery':'pickup'})},
 async inquire(){await app().request('/inquiries',{wishlist_ids:this.data.rows.map(x=>x.id),message:'小程序房间清单询价'});this.setData({tab:'inquiries'});await this.load()},
 async deleteWish(e){await app().request('/wishlist/'+e.currentTarget.dataset.id,undefined,'DELETE');await this.load()},
 async quantity(e){const row=this.data.rows.find(x=>x.id===Number(e.currentTarget.dataset.id));await app().request('/wishlist',{...row,quantity:Number(e.detail.value)});await this.load()},
 async openOrder(e){const order=await app().request('/orders/'+e.currentTarget.dataset.id);order.lines=order.lines.map(l=>({...l,priceText:app().money(l.unit_price)}));const addresses=await app().request('/addresses');this.setData({order,addresses,modal:'order',form:{delivery_mode:'pickup'}})},
 async confirm(){await app().request('/orders/'+this.data.order.id+'/confirm',{version:this.data.order.version,delivery_mode:this.data.form.delivery_mode,address_id:this.data.form.address_id||null});this.close();await this.load()},
 async cancel(){await app().request('/orders/'+this.data.order.id+'/cancel',{version:this.data.order.version});this.close();await this.load()},
 async receive(){await app().request('/orders/'+this.data.order.id+'/receive',{});this.close();await this.load()},
 async proof(e){const id=e.currentTarget.dataset.id;wx.downloadFile({url:app().globalData.baseUrl+'/api/media/'+id,header:{Authorization:'Bearer '+app().globalData.token},success:r=>{if(r.statusCode===200)wx.previewImage({urls:[r.tempFilePath]})}})},
 review(){this.setData({modal:'review',form:{sku_id:this.data.order.lines[0].sku_id,text:''}})},
 ticket(){this.setData({modal:'ticket',form:{line_id:this.data.order.lines[0].id,quantity:1,category:'damaged',description:''}})},
 itemSelect(e){const line=this.data.order.lines[Number(e.detail.value)];this.setData({'form.sku_id':line.sku_id,'form.line_id':line.id,'form.itemLabel':line.snapshot.code})},
 async attach(){const purpose=this.data.modal==='review'?'review':'ticket';const r=await app().upload(purpose);this.setData({'form.media_id':r.id})},
 async submitFeedback(){const f=this.data.form;if(this.data.modal==='review'){await app().request('/reviews',{order_id:this.data.order.id,sku_id:f.sku_id,text:f.text,media_ids:f.media_id?[f.media_id]:[]})}else{await app().request('/tickets',{order_id:this.data.order.id,line_id:f.line_id,quantity:Number(f.quantity),category:f.category,description:f.description,media_ids:f.media_id?[f.media_id]:[]})}this.close();await this.load();wx.showToast({title:'已提交 / Submitted'})},
 async quoteAction(e){await app().request('/quotes/'+e.currentTarget.dataset.id+'/action',{action:e.currentTarget.dataset.action});await this.load()},
 revise(e){const q=this.data.rows.find(x=>x.id===Number(e.currentTarget.dataset.id));this.setData({modal:'quote',form:{...q,price:q.price/100,freight:q.freight/100}})},
 async saveQuote(){const f=this.data.form;await app().request('/quotes',{sku_id:f.sku_id,price:Math.round(Number(f.price)*100),freight:Math.round(Number(f.freight)*100),available_quantity:f.available_quantity===''?null:Number(f.available_quantity),min_quantity:Number(f.min_quantity),lead_days:Number(f.lead_days),valid_until:new Date(Date.now()+30*86400000).toISOString()});this.close();await this.load()},
 newProduct(){this.setData({modal:'product',form:{category:'台灯',power_w:18,cct_k:3000,price:100}})},
 editProduct(e){const p=this.data.rows.find(x=>x.id===Number(e.currentTarget.dataset.id));this.setData({modal:'edit-product',form:{...p}})},
 async productImage(){const r=await app().upload('product');this.setData({'form.image':r.id})},
 async saveProduct(){const f=this.data.form;if(this.data.modal==='edit-product'){await app().request('/catalog/products/'+f.id,{name:f.name,title:f.title,category:f.category,description:f.description,custom:!!f.custom},'PATCH')}else{await app().request('/catalog/products',{name:f.name,title:f.title,category:f.category,description:f.description||'',skus:[{code:f.code,color:f.color||'',size_mm:f.size_mm||'',specification:f.specification||'',images:f.image?[f.image]:[],initial_price:Math.round(Number(f.price)*100),attributes:{power_w:Number(f.power_w),cct_k:Number(f.cct_k)}}]})}this.close();await this.load()},
 supplement(e){this.setData({modal:'supplement',form:{id:Number(e.currentTarget.dataset.id)}})},
 async saveSupplement(){const f=this.data.form;await app().request('/tickets/'+f.id+'/supplement',{note:f.note,media_ids:f.media_id?[f.media_id]:[]});this.close();await this.load()},
 close(){this.setData({modal:''})}
})
