const app=()=>getApp()
Page({
 data:{filterText:'',filterStatus:'',visibleRows:[],quoteFilters:[{value:'',label:'全部'},{value:'pending',label:'待审核'},{value:'rejected',label:'待修改'},{value:'expired',label:'已到期'},{value:'approved',label:'已生效'},{value:'inactive',label:'已下架'}],role:'customer',lang:'zh',tab:'wishlist',tabs:[],rows:[],modal:'',form:{},order:null,addresses:[],detail:null,selectedIds:[],roomOptions:['全部房间 / All rooms'],roomIndex:0,selectedAmount:'¥0.00',selectedQuantity:0,inquiryPreview:null,submitting:false,sendingInquiry:false,inquiryStatusIndex:0,inquiryStatusOptions:['全部 / All','待处理 / Open','已转订单 / Ordered','已撤回 / Withdrawn','已关闭 / Closed'],inquiryStatusValues:['','open','ordered','withdrawn','closed']},
 async onShow(){app().syncTabs();const next=app().globalData.nextWork;app().globalData.nextWork=null;const role=app().globalData.role;const tabs=role==='merchant'?[{key:'quotes',name:'我的报价 / Offers'},{key:'catalog',name:'我的商品 / Products'}]:[{key:'wishlist',name:'选购清单 / Lists'},{key:'inquiries',name:'询价 / Inquiries'},{key:'orders',name:'订单 / Orders'},{key:'tickets',name:'售后 / Service'}];this.setData({role,lang:app().globalData.lang,tabs,tab:next&&tabs.some(x=>x.key===next.tab)?next.tab:tabs.some(x=>x.key===this.data.tab)?this.data.tab:tabs[0].key,...(next?{filterStatus:next.status||'',filterText:''}:{})});if(app().requireLogin())await this.load()},
 async load(){
  const route=this.data.tab==='catalog'?'/admin/catalog':'/'+this.data.tab+(this.data.tab==='inquiries'&&this.data.inquiryStatusIndex?'?status='+this.data.inquiryStatusValues[this.data.inquiryStatusIndex]:'')
  let rows=await app().request(route)
  rows=rows.filter(Boolean).map(x=>({...x,statusTone:this.data.tab==='quotes'?app().quoteState(x):x.status,statusText:({pending:'待审核',approved:'已生效',rejected:'待修改',expired:'已到期',inactive:'已下架',deleted:'已删除',awaiting_confirmation:'待确认',confirmed:'已确认',fulfilling:'履约中',completed:'已完成',cancelled:'已取消',open:'待处理 / Open',ordered:'已转订单 / Ordered',withdrawn:'已撤回 / Withdrawn',closed:'已关闭 / Closed'})[this.data.tab==='quotes'?app().quoteState(x):x.status]||x.status,priceText:app().money(x.total??x.price??x.sku?.price),picture:x.sku&&x.sku.images[0]?app().picture(x.sku.images[0]):x.skus&&x.skus[0].images[0]?app().picture(x.skus[0].images[0]):'',summary:x.items?x.items.map(i=>(i.snapshot?.product_name||'SKU '+i.sku_id)+' '+(i.snapshot?.code||'')+' × '+i.quantity+' / '+i.room).join(' / '):'',estimateText:x.estimate?app().money(x.estimate.goods_amount):'',budgetText:x.requirements?.budget?app().money(x.requirements.budget):''}))
  this.setData({rows});this.filterRows()
  if(this.data.tab==='wishlist'){
   this.setData({roomOptions:['全部房间 / All rooms',...new Set(rows.map(x=>x.room))]})
   const ids=this._wishesInitialized?this.data.selectedIds.filter(id=>rows.some(x=>x.id===id)):rows.map(x=>x.id)
   this._wishesInitialized=true;this.selectIds(ids)
  }
 },
 filterRows(){const q=this.data.filterText.trim().toLowerCase();this.setData({visibleRows:this.data.rows.filter(x=>(this.data.tab!=='quotes'||!this.data.filterStatus||app().quoteState(x)===this.data.filterStatus)&&(!q||[x.id,x.number,x.sku_code,x.shop_name,x.name,x.title,x.product_name,x.description,x.summary,x.requirements?.project_name].some(v=>String(v??'').toLowerCase().includes(q))))})},
 filterInput(e){this.setData({filterText:e.detail.value});this.filterRows()},
 filterOffers(e){this.setData({filterStatus:e.currentTarget.dataset.status});this.filterRows()},
 selectIds(ids){const rows=this.data.rows.map(x=>({...x,selected:ids.includes(x.id)}));const selected=rows.filter(x=>x.selected);this.setData({rows,selectedIds:ids,selectedAmount:app().money(selected.reduce((n,x)=>n+x.sku.price*x.quantity,0)),selectedQuantity:selected.reduce((n,x)=>n+x.quantity,0),inquiryPreview:null});this.filterRows()},
 toggleWish(e){const id=Number(e.currentTarget.dataset.id);const ids=this.data.selectedIds.filter(x=>x!==id);if(e.detail.value.length)ids.push(id);this.selectIds(ids)},
 chooseRoom(e){const index=Number(e.detail.value);this.setData({roomIndex:index});this.selectIds(this.data.rows.filter(x=>!index||x.room===this.data.roomOptions[index]).map(x=>x.id))},
 inquiryPayload(){const f=this.data.form;return {wishlist_ids:this.data.selectedIds,message:f.message||'',requirements:{project_name:f.project_name||'',budget:f.budget?Math.round(Number(f.budget)*100):null,needed_by:f.needed_by||null,destination:f.destination||'',allow_alternatives:!!f.allow_alternatives}}},
 async previewInquiry(){if(this.data.submitting)return;const payload=this.inquiryPayload();this.setData({submitting:true});try{const p=await app().request('/inquiries/preview',payload);if(JSON.stringify(payload)!==JSON.stringify(this.inquiryPayload())||this.data.modal!=='inquiry'){if(this.data.modal==='inquiry')wx.showToast({title:'需求已修改，请重新预览',icon:'none'});return}p.amountText=app().money(p.estimate.goods_amount);p.gapText=app().money(p.estimate.budget_gap);p.estimate.rooms=p.estimate.rooms.map(r=>({...r,amountText:app().money(r.amount)}));this.setData({inquiryPreview:p})}finally{this.setData({submitting:false})}},
 async submitInquiry(){if(this.data.submitting||!this.data.inquiryPreview?.can_submit)return;this.setData({submitting:true,sendingInquiry:true});const payload=this.inquiryPayload(),signature=JSON.stringify(payload);if(this._submissionSignature!==signature){this._submissionSignature=signature;this._submissionKey=app().submissionKey()}try{await app().request('/inquiries',{...payload,submission_key:this._submissionKey});this._submissionSignature=null;this.setData({modal:'',tab:'inquiries'});await this.load()}finally{this.setData({submitting:false,sendingInquiry:false})}},

 inquiryStatus(e){this.setData({inquiryStatusIndex:Number(e.detail.value)});this.load()},
 async openInquiry(e){const detail=await app().request('/inquiries/'+e.currentTarget.dataset.id);this.setData({detail,modal:'inquiry-detail',form:{reply:'',reason:'',withdraw:false}})},
 async inquiryReply(){if(this.data.submitting)return;this.setData({submitting:true});try{const detail=await app().request('/inquiries/'+this.data.detail.id+'/messages',{message:this.data.form.reply});this.setData({detail,'form.reply':''});await this.load()}finally{this.setData({submitting:false})}},
 beginWithdrawal(){this.setData({'form.withdraw':true})},
 cancelWithdrawal(){this.setData({'form.withdraw':false})},
 async withdrawInquiry(){if(this.data.submitting)return;this.setData({submitting:true});try{const detail=await app().request('/inquiries/'+this.data.detail.id+'/withdraw',{message:this.data.form.reason});this.setData({detail,'form.withdraw':false});await this.load()}finally{this.setData({submitting:false})}},
 async linkedOrder(){await this.openOrder({currentTarget:{dataset:{id:this.data.detail.order_id}}})},
 async tab(e){this.setData({tab:e.currentTarget.dataset.key,filterText:'',filterStatus:''});await this.load()},
 input(e){if(this.data.sendingInquiry)return;this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value,...(this.data.modal==='inquiry'?{inquiryPreview:null}:{})})},
 selectAddress(e){const index=Number(e.detail.value);this.setData({'form.address_id':this.data.addresses[index].id,'form.address_label':this.data.addresses[index].detail})},
 delivery(e){this.setData({'form.delivery_mode':e.detail.value?'delivery':'pickup'})},
 inquire(){if(!this.data.selectedIds.length){wx.showToast({title:'请先勾选商品',icon:'none'});return}this.setData({modal:'inquiry',form:{allow_alternatives:false},inquiryPreview:null})},
 async deleteWish(e){await app().request('/wishlist/'+e.currentTarget.dataset.id,undefined,'DELETE');await this.load()},
 editWish(e){const row=this.data.rows.find(x=>x.id===Number(e.currentTarget.dataset.id));this.setData({modal:'wish',form:{id:row.id,version:row.version,room:row.room,quantity:row.quantity,note:row.note,watch_price:row.watch_price,watch_stock:row.watch_stock}})},
 async saveWish(){if(this.data.submitting)return;const f=this.data.form;if(!f.room.trim()||!Number.isInteger(Number(f.quantity))||Number(f.quantity)<1||Number(f.quantity)>100000){wx.showToast({title:'填写房间和有效整数数量',icon:'none'});return}this.setData({submitting:true});try{await app().request('/wishlist/'+f.id,{version:f.version,room:f.room,quantity:Number(f.quantity),note:f.note,watch_price:f.watch_price,watch_stock:f.watch_stock},'PATCH');this.setData({modal:''});await this.load()}finally{this.setData({submitting:false})}},
 async openOrder(e){const order=await app().request('/orders/'+e.currentTarget.dataset.id);order.lines=order.lines.map(l=>({...l,priceText:app().money(l.unit_price)}));const addresses=await app().request('/addresses');this.setData({order,addresses,modal:'order',form:{delivery_mode:'pickup'}})},
 async confirm(){await app().request('/orders/'+this.data.order.id+'/confirm',{version:this.data.order.version,delivery_mode:this.data.form.delivery_mode,address_id:this.data.form.address_id||null});this.close();await this.load()},
 async cancel(){await app().request('/orders/'+this.data.order.id+'/cancel',{version:this.data.order.version});this.close();await this.load()},
 async receive(){await app().request('/orders/'+this.data.order.id+'/receive',{});this.close();await this.load()},
 async proof(e){const id=e.currentTarget.dataset.id;wx.downloadFile({url:app().globalData.baseUrl+'/api/media/'+id,header:{Authorization:'Bearer '+app().globalData.token},success:r=>{if(r.statusCode===200)wx.previewImage({urls:[r.tempFilePath]})}})},
 review(){this.setData({modal:'review',form:{sku_id:this.data.order.lines[0].sku_id,text:''}})},
 ticket(){this.setData({modal:'ticket',form:{line_id:this.data.order.lines[0].id,quantity:1,category:'damaged',description:''}})},
 itemSelect(e){const line=this.data.order.lines[Number(e.detail.value)];this.setData({'form.sku_id':line.sku_id,'form.line_id':line.id,'form.itemLabel':line.snapshot.code})},
 async attach(){const purpose=this.data.modal==='review'?'review':'ticket';const r=await app().upload(purpose);this.setData({'form.media_id':r.id})},
 async submitFeedback(){const f=this.data.form;if(this.data.modal==='review'){await app().request('/reviews',{order_id:this.data.order.id,sku_id:f.sku_id,text:f.text,media_ids:f.media_id?[f.media_id]:[]})}else{await app().request('/tickets',{order_id:this.data.order.id,line_id:f.line_id,quantity:Number(f.quantity),category:f.category,description:f.description,media_ids:f.media_id?[f.media_id]:[]})}this.close();await this.load();wx.showToast({title:'已提交 / Submitted'})},
 async quoteAction(e){await app().request('/quotes/'+e.currentTarget.dataset.id+'/action',{action:e.currentTarget.dataset.action});await this.load()},
 revise(e){const q=this.data.rows.find(x=>x.id===Number(e.currentTarget.dataset.id));this.setData({modal:'quote',form:{...q,price:q.price/100,freight:q.freight/100}})},
 async saveQuote(){const f=this.data.form;await app().request('/quotes',{sku_id:f.sku_id,price:Math.round(Number(f.price)*100),freight:Math.round(Number(f.freight)*100),available_quantity:f.available_quantity===''?null:Number(f.available_quantity),min_quantity:Number(f.min_quantity),lead_days:Number(f.lead_days),valid_until:new Date(Date.now()+30*86400000).toISOString()});this.close();await this.load()},
 newProduct(){this.setData({modal:'product',form:{category:'台灯',power_w:18,cct_k:3000,price:100}})},
 editProduct(e){const p=this.data.rows.find(x=>x.id===Number(e.currentTarget.dataset.id));this.setData({modal:'edit-product',form:{...p}})},
 async productImage(){const r=await app().upload('product');this.setData({'form.image':r.id})},
 async saveProduct(){const f=this.data.form;if(this.data.modal==='edit-product'){await app().request('/catalog/products/'+f.id,{name:f.name,title:f.title,category:f.category,description:f.description,custom:!!f.custom},'PATCH')}else{await app().request('/catalog/products',{name:f.name,title:f.title,category:f.category,description:f.description||'',skus:[{code:f.code,color:f.color||'',size_mm:f.size_mm||'',specification:f.specification||'',images:f.image?[f.image]:[],initial_price:Math.round(Number(f.price)*100),attributes:{power_w:Number(f.power_w),cct_k:Number(f.cct_k)}}]})}this.close();await this.load()},
 supplement(e){this.setData({modal:'supplement',form:{id:Number(e.currentTarget.dataset.id)}})},
 async saveSupplement(){const f=this.data.form;await app().request('/tickets/'+f.id+'/supplement',{note:f.note,media_ids:f.media_id?[f.media_id]:[]});this.close();await this.load()},
 close(){if(!this.data.submitting)this.setData({modal:''})}
})
