<script setup lang="ts">
import {ref,reactive} from 'vue'
import {api,money,upload} from './api'
const props=defineProps<{page:string,user:any,products:any[]}>(),emit=defineEmits(['refresh'])
const mode=ref(''),error=ref(''),busy=ref(false),items=ref<any[]>([]),preview=ref<any[]>([]),form=reactive<any>({}),batch=ref<any[]>([])
async function run(fn:()=>Promise<any>){busy.value=true;error.value='';try{await fn()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function open(name:string){mode.value=name;error.value='';items.value=[];preview.value=[];Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,{multiplier:1.3,product_id:props.products[0]?.id,permissions:[],active:true,unit:'个',power_w:18,cct_k:3000});if(name==='changes')await run(async()=>{items.value=await api('/admin/catalog/changes')});if(name==='staff-edit')await run(async()=>{items.value=(await api('/admin/users')).filter((x:any)=>x.role==='staff')})}
async function pricingPreview(){await run(async()=>{preview.value=await api('/admin/pricing/preview',{multiplier_bp:Math.round(Number(form.multiplier)*10000)})})}
async function savePricing(){await run(async()=>{await api('/admin/pricing',{multiplier_bp:Math.round(Number(form.multiplier)*10000)});mode.value='';emit('refresh')})}
async function decide(change:any,approve:boolean){await run(async()=>{await api('/admin/catalog/changes/'+change.id+'/review',{approve,reason:approve?'':form.reason||''});items.value=await api('/admin/catalog/changes');emit('refresh')})}
async function image(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f)await run(async()=>{form.image=(await upload(f,'product')).id})}
async function addSku(){await run(async()=>{await api('/catalog/products/'+form.product_id+'/skus',{code:form.code,color:form.color||'',size_mm:form.size_mm||'',specification:form.specification||'',unit:form.unit,initial_price:Math.round(Number(form.price)*100),images:form.image?[form.image]:[],attributes:{power_w:Number(form.power_w),cct_k:Number(form.cct_k)}});mode.value='';emit('refresh')})}
async function pendingSkus(){await open('sku-review');items.value=(await api('/admin/catalog')).filter(Boolean).flatMap((p:any)=>p.skus.filter((s:any)=>s.status==='pending').map((s:any)=>({...s,name:p.name})))}
async function skuApprove(s:any,status:string){await run(async()=>{await api('/admin/skus/'+s.id+'/state',{status,reason:form.reason||''});items.value=items.value.filter(x=>x.id!==s.id);emit('refresh')})}
async function selectStaff(){const s=items.value.find(x=>x.id===Number(form.id));if(s)Object.assign(form,{id:s.id,name:s.name,permissions:[...s.permissions],active:s.active})}
async function saveStaff(){await run(async()=>{await api('/admin/staff/'+form.id,{name:form.name,permissions:form.permissions,active:form.active},'PATCH');mode.value='';emit('refresh')})}
async function parseCsv(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;await run(async()=>{const lines=(await file.text()).replace(/^\uFEFF/,'').trim().split(/\r?\n/);const header=lines.shift()!.split(',').map(s=>s.trim());const skus=props.products.flatMap(p=>p.skus);batch.value=lines.map(line=>{const values=line.split(',');const row:any={};header.forEach((k,i)=>row[k]=values[i]?.trim());const sku=skus.find(s=>s.code===row.sku_code);if(!sku)throw Error('未找到 SKU '+row.sku_code);return {sku_id:sku.id,price:Math.round(Number(row.price_yuan)*100),available_quantity:row.quantity===''?null:Number(row.quantity),min_quantity:Number(row.min_quantity||1),lead_days:Number(row.lead_days||3),freight:Math.round(Number(row.freight_yuan||0)*100),valid_until:row.valid_until+'T23:59:59'}});const result=await api('/quotes/import',{rows:batch.value,commit:false});preview.value=result.errors;if(!result.valid)throw Error('导入包含错误，请修正后重新上传')})}
async function importBatch(){await run(async()=>{await api('/quotes/import',{rows:batch.value,commit:true});mode.value='';emit('refresh')})}
function csvTemplate(){const text='sku_code,price_yuan,quantity,min_quantity,lead_days,freight_yuan,valid_until\nLM-001-1,120.00,30,1,3,10.00,2027-01-01\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv'}));a.download='报价导入模板.csv';a.click();URL.revokeObjectURL(a.href)}
</script>
<template>
  <div class="table-actions" style="margin-bottom:22px" v-if="page==='catalog'||page==='quotes'&&user.role==='merchant'||page==='users'&&user.role==='admin'">
    <template v-if="page==='catalog'"><button class="secondary" @click="open('add-sku')">新增规格 / Add SKU</button><template v-if="user.role!=='merchant'"><button class="secondary" @click="open('changes')">资料变更审核 / Changes</button><button class="secondary" @click="pendingSkus">规格审核 / SKU review</button><button class="secondary" @click="open('pricing')">定价规则 / Pricing</button></template></template>
    <button v-if="page==='quotes'" class="secondary" @click="open('import')">批量报价导入 / Import offers</button><button v-if="page==='users'" class="secondary" @click="open('staff-edit')">编辑员工与权限 / Permissions</button>
  </div>
  <div v-if="mode" class="overlay" @click.self="mode=''"><section class="dialog wide"><button class="close" @click="mode=''">×</button><p v-if="error" class="error">{{error}}</p>
    <template v-if="mode==='pricing'"><h2>定价规则预览 / Pricing preview</h2><p>展示价按基准价直接乘以下方乘数，人工最终价优先。历史订单金额不变。</p><label>价格乘数 / Multiplier<input v-model="form.multiplier" type="number" min="0.1" max="10" step="0.01" @input="preview=[]"/></label><button class="secondary" @click="pricingPreview">预览影响 / Preview</button><div style="max-height:330px;overflow:auto"><table v-if="preview.length"><thead><tr><th>SKU</th><th>原价 / Current</th><th>新价 / Proposed</th></tr></thead><tbody><tr v-for="p in preview"><td>{{p.code}}</td><td>{{money(p.old)}}</td><td>{{money(p.new)}}</td></tr></tbody></table></div><button class="primary full" v-if="preview.length" @click="savePricing" :disabled="busy">确认发布新版本 / Publish version</button></template>
    <template v-else-if="mode==='changes'"><h2>商品资料变更审核 / Changes</h2><div v-for="c in items" class="panel"><span class="badge">{{c.status}}</span><table><thead><tr><th>字段</th><th>修改前</th><th>修改后</th></tr></thead><tbody><tr v-for="(v,k) in c.payload"><td>{{k}}</td><td>{{c.before[k]}}</td><td>{{v}}</td></tr></tbody></table><template v-if="c.status==='pending'"><input v-model="form.reason" placeholder="驳回原因 / Rejection reason"/><div class="table-actions"><button @click="decide(c,true)">通过 / Approve</button><button @click="decide(c,false)">驳回 / Reject</button></div></template></div><p v-if="!items.length">没有待审核资料。</p></template>
    <template v-else-if="mode==='sku-review'"><h2>新增规格审核 / SKU review</h2><div v-for="s in items" class="list-item"><div><b>{{s.name}} · {{s.code}}</b><p>{{s.specification}} / {{s.size_mm}}</p></div><button @click="skuApprove(s,'active')">通过</button><button @click="skuApprove(s,'rejected')">驳回</button></div><p v-if="!items.length">没有待审核规格。</p></template>
    <form v-else-if="mode==='add-sku'" @submit.prevent="addSku"><h2>新增商品规格 / Add variant</h2><label>商品 / Product<select v-model="form.product_id"><option v-for="p in products" :value="p.id">{{p.name}}</option></select></label><div class="form-grid"><label>SKU 编码<input v-model="form.code" required/></label><label>颜色 / Color<input v-model="form.color"/></label><label>尺寸 mm<input v-model="form.size_mm"/></label><label>规格 / Specification<input v-model="form.specification"/></label><label>单位 / Unit<input v-model="form.unit"/></label><label>初始价格 元<input v-model="form.price" type="number" min="0" step="0.01" required/></label><label>功率 W<input v-model="form.power_w" type="number" min="0" required/></label><label>色温 K<input v-model="form.cct_k" type="number" min="0" required/></label></div><input type="file" accept="image/*" @change="image" required/><button class="primary full" :disabled="busy">保存并审核 / Save</button></form>
    <form v-else-if="mode==='staff-edit'" @submit.prevent="saveStaff"><h2>员工权限 / Staff permissions</h2><label>员工<select v-model="form.id" @change="selectStaff" required><option v-for="s in items" :value="s.id">{{s.username}}</option></select></label><label>姓名<input v-model="form.name" required/></label><div class="permission-grid"><label v-for="m in ['users','merchants','catalog','quotes','orders','procurement','operations','reports']" class="check"><input type="checkbox" v-model="form.permissions" :value="m"/>{{m}}</label></div><label class="check"><input type="checkbox" v-model="form.active"/>账户启用 / Active</label><button class="primary full" :disabled="busy">保存权限 / Save permissions</button></form>
    <template v-else-if="mode==='import'"><h2>批量报价 / Batch offers</h2><p>先下载模板。填写 SKU 编码、单价、可供数量、起订量、交期、运费及有效日期。上传后先校验，再提交审核。</p><button class="secondary" @click="csvTemplate">下载 CSV 模板 / Template</button><label>报价 CSV 文件<input type="file" accept=".csv" @change="parseCsv"/></label><p>{{batch.length}} 行 / rows</p><div class="error" v-for="p in preview">第 {{p.row}} 行：{{p.message}}</div><button v-if="batch.length&&!preview.length&&!error" class="primary" @click="importBatch" :disabled="busy">确认导入并提交审核 / Import</button></template>
  </section></div>
</template>
