<script setup lang="ts">
import { ref, reactive, computed, onMounted, watch } from 'vue'
import { Sun, Search, ScanLine, ArrowUpRight, ArrowRight, LayoutDashboard, Package, ClipboardList, Truck, Store, Users, Settings2, Bell, LogOut, Plus, Check, X, SlidersHorizontal, Heart, MessageSquare, ImagePlus, RefreshCw, Layers, ChartNoAxesCombined, ChevronRight, Languages, CircleHelp, ShieldCheck } from 'lucide-vue-next'
import { api, upload, mediaUrl, money } from './api'
const window = globalThis.window

const user = ref<any>(null), token = ref(localStorage.getItem('luma-token')), page = ref('home'), lang = ref(localStorage.getItem('luma-lang') || 'zh')
const busy = ref(false), error = ref(''), toast = ref(''), catalog = ref<any[]>([]), categories = ref<string[]>([]), rows = ref<any[]>([]), settings = ref<any>({}), dashboard = ref<any>({}), notifications = ref<any[]>([])
const selected = ref<any>(null), skuId = ref<number>(0), searchText = ref(''), category = ref(''), maxPrice = ref(''), searchImage = ref<any>(null), searchResult = ref<any>(null), cropEnabled = ref(false), crop = reactive({ x:0, y:0, w:1, h:1 }), availableOnly = ref(false)
const modal = ref(''), form = reactive<any>({}), modalRows = ref<any[]>([]), detailOrder = ref<any>(null), compareIds = ref<number[]>([]), compareOpen = ref(false)
const loginMode = ref('login'), credentials = reactive({ username:'', password:'', phone:'', code:'', role:'customer', agreement:false }), developmentCode = ref('')
const t = (zh:string, en:string) => lang.value === 'zh' ? zh : en
const isAdmin = computed(() => ['admin','staff'].includes(user.value?.role)), isMerchant = computed(() => user.value?.role === 'merchant')
const activeSku = computed(() => selected.value?.skus.find((s:any) => s.id === Number(skuId.value)))
const compareSkus = computed(() => catalog.value.flatMap(p => p.skus.map((s:any) => ({...s,product_name:p.name}))).filter(s=>compareIds.value.includes(s.id)))
const stateNames:any = {active:'已上架',inactive:'已下架',pending:'待审核',approved:'已通过',rejected:'已驳回',disabled:'已禁用',deleted:'已删除',awaiting_confirmation:'待客户确认',confirmed:'已确认',fulfilling:'履约中',completed:'已完成',cancelled:'已取消',draft:'待采购',planned:'方案待确认',processing:'处理中',exception:'异常',available:'有货',unavailable:'缺货',unconfirmed:'供货量待确认',open:'待处理',ordered:'已转订单',need_information:'待补充',resolved:'已解决',closed:'已关闭',failed:'失败',running:'执行中',partial:'部分发货',shipped:'已发货',unshipped:'未发货'}
const state = (s:string) => lang.value === 'en' ? s : stateNames[s] || s
const nav = computed(() => {
  const admin = [{id:'dashboard',zh:'工作总览',en:'Overview',icon:LayoutDashboard,module:'reports'},{id:'catalog',zh:'商品与规格',en:'Catalog',icon:Package,module:'catalog'},{id:'quotes',zh:'报价审核',en:'Quotes',icon:Layers,module:'quotes'},{id:'merchants',zh:'商家认证',en:'Merchants',icon:Store,module:'merchants'},{id:'users',zh:'客户与权限',en:'People',icon:Users,module:'users'},{id:'inquiries',zh:'客户询价',en:'Inquiries',icon:MessageSquare,module:'orders'},{id:'orders',zh:'销售订单',en:'Orders',icon:ClipboardList,module:'orders'},{id:'procurements',zh:'采购协同',en:'Procurement',icon:Truck,module:'procurement'},{id:'tickets',zh:'售后工单',en:'After-sales',icon:CircleHelp,module:'orders'},{id:'reviews',zh:'商品评价',en:'Reviews',icon:MessageSquare,module:'operations'},{id:'settings',zh:'运营设置',en:'Settings',icon:Settings2,module:'operations'},{id:'index',zh:'检索索引',en:'Search index',icon:ScanLine,module:'catalog'},{id:'exceptions',zh:'异常中心',en:'Exceptions',icon:ShieldCheck,module:'reports'},{id:'audits',zh:'操作记录',en:'Audit trail',icon:ChartNoAxesCombined,module:'reports'}]
  if(isAdmin.value) return admin.filter(x=>user.value.role==='admin'||user.value.permissions.includes(x.module))
  if(isMerchant.value) return [{id:'home',zh:'供货选品',en:'Catalog',icon:Store},{id:'quotes',zh:'我的报价',en:'My quotes',icon:Layers},{id:'catalog',zh:'我的商品',en:'My products',icon:Package},{id:'profile',zh:'商家认证',en:'Verification',icon:ShieldCheck}]
  return [{id:'home',zh:'发现灯具',en:'Discover',icon:Sun},{id:'wishlist',zh:'房间清单',en:'Room lists',icon:Heart},{id:'inquiries',zh:'我的询价',en:'Inquiries',icon:MessageSquare},{id:'orders',zh:'我的订单',en:'Orders',icon:ClipboardList},{id:'tickets',zh:'售后服务',en:'After-sales',icon:CircleHelp},{id:'profile',zh:'个人资料',en:'Profile',icon:Users}]
})
const currentTitle = computed(()=>{const n=nav.value.find(n=>n.id===page.value);return n?t(n.zh,n.en):t('消息中心','Notifications')})
const filteredCatalog = computed(()=>catalog.value.filter(p=>(!category.value||p.category===category.value)))
const shownProducts = computed(()=>searchResult.value ? searchResult.value.results.map((r:any)=>{const p=catalog.value.find(p=>p.id===r.product_id);return p?{...p,selected_sku_id:r.sku_id,min_price:r.price,search_hit:r}:null}).filter(Boolean):filteredCatalog.value)
const unread = computed(()=>notifications.value.filter(n=>!n.read).length)
const key = ()=>crypto.randomUUID()
async function action(fn:()=>Promise<any>, message=t('已保存','Saved')) { if(busy.value)return;busy.value=true;error.value='';try {const r=await fn();if(message){toast.value=message;setTimeout(()=>toast.value='',4000)}return r}catch(e:any){error.value=e.message;return null}finally{busy.value=false} }
async function boot(){categories.value=await api('/catalog/categories');catalog.value=await api('/catalog/products');settings.value=await api('/settings');if(token.value){try{user.value=await api('/me');page.value=isAdmin.value?(nav.value[0]?.id||'home'):'home';await load()}catch{localStorage.removeItem('luma-token');token.value=null}}}
async function signin(){await action(async()=>{let result;if(loginMode.value==='register'){result=await api('/auth/register',credentials)}else if(loginMode.value==='reset'){await api('/auth/reset',credentials);loginMode.value='login';return}else if(loginMode.value==='code'){result=await api('/auth/login-code',credentials)}else result=await api('/auth/login',credentials);token.value=result.token;localStorage.setItem('luma-token',result.token);user.value=result.user;page.value=isAdmin.value?(nav.value[0]?.id||'home'):'home';await load()},'')}
async function sendCode(){await action(async()=>{const r=await api('/auth/code',{phone:credentials.phone});developmentCode.value=r.development_code||''},t('验证码已发送','Code sent'))}
async function signout(){await api('/auth/logout',{});localStorage.removeItem('luma-token');token.value=null;user.value=null;selected.value=null;modal.value='';page.value='home'}
async function load(){error.value='';rows.value=[];if(!user.value)return;notifications.value=await api('/notifications');const map:any={catalog:'/admin/catalog',quotes:'/quotes',merchants:'/admin/merchants',users:'/admin/users',orders:'/orders',inquiries:'/inquiries',procurements:'/procurements',tickets:'/tickets',reviews:'/reviews',exceptions:'/admin/exceptions',audits:'/admin/audits',wishlist:'/wishlist'};if(map[page.value])rows.value=(await api(map[page.value])).filter(Boolean);if(page.value==='dashboard')dashboard.value=await api('/admin/dashboard');if(page.value==='index')dashboard.value=await api('/admin/index');if(page.value==='settings')settings.value=await api('/settings');if(page.value==='profile'){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,isMerchant.value?await api('/merchant/profile'):{...user.value});if(!isMerchant.value)rows.value=await api('/addresses')};if(page.value==='home')catalog.value=await api('/catalog/products')}
watch(page,()=>load().catch(e=>error.value=e.message));watch(lang,v=>localStorage.setItem('luma-lang',v));onMounted(()=>action(boot,''))
function openModal(name:string,data:any={}){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,data);modal.value=name;error.value=''}
async function openProduct(p:any){selected.value=await api('/catalog/products/'+p.id+'?sku='+p.selected_sku_id);skuId.value=p.selected_sku_id;modalRows.value=await api('/reviews?sku_id='+skuId.value)}
async function runSearch(){await action(async()=>{if(!user.value)throw Error(t('请先登录以使用多模态检索','Sign in to use visual search'));searchResult.value=await api('/search',{image_id:searchImage.value?.id||null,text:searchText.value,category:category.value,max_price:maxPrice.value?Math.round(Number(maxPrice.value)*100):null,available_only:availableOnly.value,crop:cropEnabled.value?[Number(crop.x),Number(crop.y),Number(crop.w),Number(crop.h)]:null})},'')}
async function fileInput(event:Event,purpose:string,target:string){const f=(event.target as HTMLInputElement).files?.[0];if(!f)return;await action(async()=>{const r=await upload(f,purpose);if(target==='search'){searchImage.value={...r,preview:URL.createObjectURL(f)}}else{form[target]=r.id;form[target+'_preview']=URL.createObjectURL(f)}},t('上传完成','Uploaded'))}
function toggleCompare(id:number){if(compareIds.value.includes(id))compareIds.value=compareIds.value.filter(x=>x!==id);else if(compareIds.value.length<4)compareIds.value.push(id);else error.value=t('最多对比 4 个规格','Compare up to 4 variants')}
async function saveWish(){await action(async()=>{await api('/wishlist',{sku_id:activeSku.value.id,quantity:1,room:form.room||t('客厅','Living room'),watch_price:true});selected.value=null},t('已加入房间清单','Added to room list'))}
function quoteForm(s:any){openModal('quote',{sku_id:s.id,sku_code:s.code,price:'',available_quantity:20,min_quantity:1,lead_days:3,freight:0,valid_until:new Date(Date.now()+30*864e5).toISOString().slice(0,10)})}
async function saveQuote(){await action(async()=>{await api('/quotes',{sku_id:Number(form.sku_id),price:Math.round(Number(form.price)*100),available_quantity:form.available_quantity===''?null:Number(form.available_quantity),min_quantity:Number(form.min_quantity),lead_days:Number(form.lead_days),freight:Math.round(Number(form.freight)*100),valid_until:form.valid_until+'T23:59:59'});modal.value='';selected.value=null;page.value='quotes';await load()})}
async function review(path:string,id:number,approve:boolean){if(!approve){openModal('reject',{path,id,reason:''});return}await action(async()=>{await api(path+'/'+id+'/review',{approve:true});await load()})}
async function reject(){await action(async()=>{await api(form.path+'/'+form.id+'/review',{approve:false,reason:form.reason});modal.value='';await load()})}
async function changeCatalog(p:any,status:string){await action(async()=>{await api('/admin/catalog/'+p.id+'/state',{status});await load()})}
async function openOrder(o:any){await action(async()=>{detailOrder.value=await api('/orders/'+o.id);openModal('order-detail');modalRows.value=user.value.role==='customer'?await api('/addresses'):[]},'')}
async function confirmOrder(){await action(async()=>{await api('/orders/'+detailOrder.value.id+'/confirm',{version:detailOrder.value.version,delivery_mode:form.delivery_mode||'pickup',address_id:form.delivery_mode==='delivery'?Number(form.address_id):null});modal.value='';await load()})}
async function newOrder(inquiry:any=null){openModal('new-order',{customer_id:inquiry?.user_id||'',items:inquiry?.items.map((x:any)=>({...x,unit_price:''}))||[{sku_id:'',quantity:1,unit_price:''}],remark:inquiry?.message||'',inquiry_id:inquiry?.id||null});modalRows.value=await api('/admin/users?role=customer')}
async function saveOrder(){await action(async()=>{const grouped:any={};for(const item of form.items){const sid=Number(item.sku_id);if(grouped[sid])grouped[sid].quantity+=Number(item.quantity);else grouped[sid]={sku_id:sid,quantity:Number(item.quantity),unit_price:item.unit_price===''?null:Math.round(Number(item.unit_price)*100)}}await api('/orders',{customer_id:Number(form.customer_id),items:Object.values(grouped),remark:form.remark,inquiry_id:form.inquiry_id,idempotency_key:key()});modal.value='';page.value='orders';await load()})}
async function plan(p:any){await action(async()=>{const r=await api('/orders/'+p.order_id+'/procurement/plan',{max_days:Number(form.max_days||30),max_suppliers:form.max_suppliers?Number(form.max_suppliers):null,budget:form.budget?Math.round(Number(form.budget)*100):null});openModal('plan-result',{...r});await load()},'')}
async function confirmPlan(p:any){await action(async()=>{await api('/orders/'+p.order_id+'/procurement/confirm',{version:p.version});modal.value='';await load()})}
async function completeProcurement(){await action(async()=>{await api('/orders/'+form.order_id+'/procurement/complete',{media_ids:[form.proof]});modal.value='';await load()})}
async function shipOrder(){await action(async()=>{await api('/orders/'+detailOrder.value.id+'/shipments',{idempotency_key:key(),carrier:form.carrier||'',tracking:form.tracking||'',proof_media_ids:[form.proof],items:detailOrder.value.lines.filter((l:any)=>Number(form['qty_'+l.id])>0).map((l:any)=>({line_id:l.id,quantity:Number(form['qty_'+l.id])}))});modal.value='';await load()})}
async function receiveOrder(o:any){await action(async()=>{await api('/orders/'+o.id+'/receive',{});modal.value='';await load()})}
async function makeInquiry(){await action(async()=>{await api('/inquiries',{wishlist_ids:rows.value.map(x=>x.id),message:form.message||''});page.value='inquiries';await load()})}
async function saveProfile(){await action(async()=>{if(isMerchant.value){await api('/merchant/profile',{shop_name:form.shop_name,legal_name:form.legal_name,phone:form.phone,address:form.address,license_media_id:form.license_media_id},'PUT')}else{user.value=await api('/me',{username:form.username,name:form.name},'PATCH')}await load()})}
async function saveAddress(){await action(async()=>{await api('/addresses',{recipient:form.recipient,phone:form.phone,detail:form.detail});modal.value='';await load()})}
async function saveProduct(){await action(async()=>{await api('/catalog/products',{name:form.name,title:form.title,category:form.category,description:form.description||'',custom:!!form.custom,skus:[{code:form.code,color:form.color||'',size_mm:form.size_mm||'',specification:form.specification||'',initial_price:Math.round(Number(form.price)*100),images:form.image?[form.image]:[],attributes:{power_w:Number(form.power_w),cct_k:Number(form.cct_k)},stock_status:form.stock_status||'available'}]});modal.value='';await load()})}
async function saveTicket(){await action(async()=>{await api('/tickets',{order_id:detailOrder.value.id,line_id:Number(form.line_id),quantity:Number(form.quantity),category:form.category,description:form.description,media_ids:form.attachment?[form.attachment]:[]});modal.value='';page.value='tickets';await load()})}
async function saveReview(){await action(async()=>{await api('/reviews',{order_id:detailOrder.value.id,sku_id:Number(form.sku_id),text:form.text,media_ids:form.attachment?[form.attachment]:[]});modal.value='';await load()})}
async function submitGeneric(){await action(async()=>{if(modal.value==='staff'){await api('/admin/staff',{username:form.username,name:form.name,password:form.password,permissions:form.permissions||[]})}else if(modal.value==='reply'){await api('/reviews/'+form.id,{reply:form.reply,deleted:!!form.deleted},'PATCH')}else if(modal.value==='ticket-update'){await api('/tickets/'+form.id,{status:form.status,note:form.note},'PATCH')}else if(modal.value==='ticket-supplement'){await api('/tickets/'+form.id+'/supplement',{note:form.note,media_ids:form.attachment?[form.attachment]:[]})}else if(modal.value==='password'){await api('/auth/password',{old_password:form.old_password,new_password:form.new_password});await signout()}else if(modal.value==='sku-price'){await api('/admin/skus/'+form.id+'/price',{manual_price:form.price===''?null:Math.round(Number(form.price)*100),stock_status:form.stock_status},'PATCH')}else if(modal.value==='edit-product'){await api('/catalog/products/'+form.id,{name:form.name,title:form.title,category:form.category,description:form.description,custom:form.custom},'PATCH')}modal.value='';await load()})}
async function saveSettings(){await action(async()=>{await api('/settings',settings.value,'PUT')})}
async function settingUpload(event:Event,key:string,index:number){const f=(event.target as HTMLInputElement).files?.[0];if(!f)return;await action(async()=>{const r=await upload(f,key==='support'?'support':'banner');settings.value[key][index].image=r.id})}
async function privateMedia(id:string){await action(async()=>{const r=await fetch('/api/media/'+encodeURIComponent(id),{headers:{Authorization:'Bearer '+token.value}});if(!r.ok)throw Error('附件无权访问');const url=URL.createObjectURL(await r.blob());window.open(url,'_blank','noopener')},'')}
function shareSku(){const url=location.origin+'/#product='+selected.value.id+'&sku='+skuId.value;navigator.clipboard.writeText(url);toast.value=t('商品与规格链接已复制','Product and variant link copied')}
onMounted(()=>{const p=new URLSearchParams(location.hash.slice(1));if(p.has('product'))api('/catalog/products/'+p.get('product')+'?sku='+p.get('sku')).then(r=>{selected.value=r;skuId.value=Number(p.get('sku'))}).catch(e=>error.value=e.message)})
</script>

<template>
  <div v-if="!user" class="auth-layout">
    <section class="auth-story"><a class="brand"><Sun :size="32"/><b>Luma<span>Supply</span></b></a><div class="auth-copy"><span class="eyebrow">LIGHTING · SOURCING · TOGETHER</span><h1>让好设计，<br>遇见合适的光。</h1><p>从一张灵感图片，到每一件如期抵达的灯具。<br>连接选灯、报价与采购的协同工作空间。</p><div class="auth-stats"><span><b>01</b> 图文找灯</span><span><b>02</b> 多商家协同</span><span><b>03</b> 采购优化</span></div></div><div class="lamp-art"><div class="cord"></div><div class="shade"></div><div class="light-cone"></div></div><small>综合课程项目 · 本地演示资料 · 无在线支付</small></section>
    <section class="auth-panel"><button class="language" @click="lang=lang==='zh'?'en':'zh'"><Languages :size="16"/>{{lang==='zh'?'English':'中文'}}</button><div class="auth-form"><span class="eyebrow">WELCOME TO LUMASUPPLY</span><h2>{{loginMode==='register'?t('创建账户','Create account'):loginMode==='reset'?t('找回密码','Reset password'):t('欢迎回来','Welcome back')}}</h2><p class="muted">{{t('登录您的灯具协同工作空间','Sign in to your lighting workspace')}}</p><form @submit.prevent="signin">
      <label v-if="['login','register'].includes(loginMode)">{{t('用户名','Username')}}<input v-model="credentials.username" required autocomplete="username" :placeholder="t('输入用户名','Username')"/></label>
      <label v-if="loginMode!=='login'">{{t('手机号','Phone')}}<input v-model="credentials.phone" required placeholder="138…"/></label>
      <label v-if="loginMode!=='login'">{{t('验证码','Verification code')}}<div class="inline"><input v-model="credentials.code" required/><button type="button" class="secondary" @click="sendCode">{{t('获取验证码','Send code')}}</button></div><small v-if="developmentCode">本地开发验证码：{{developmentCode}}（未发送短信）</small></label>
      <label v-if="loginMode!=='code'">{{t('密码','Password')}}<input v-model="credentials.password" type="password" required :minlength="loginMode==='login'?1:8" autocomplete="current-password"/></label>
      <template v-if="loginMode==='register'"><label>{{t('账户类型','Account type')}}<select v-model="credentials.role"><option value="customer">{{t('客户','Customer')}}</option><option value="merchant">{{t('商家','Merchant')}}</option></select></label><label class="check"><input v-model="credentials.agreement" type="checkbox" required/>{{t('同意注册协议与隐私说明：资料仅用于账户与业务履约；搜图不默认用于训练。','I agree to account and fulfillment processing; search images are not used for training.')}}</label></template>
      <div v-if="error" class="error">{{error}}</div><button class="primary full" :disabled="busy">{{t('继续','Continue')}}<ArrowRight :size="18"/></button></form><div class="auth-links"><button @click="loginMode=loginMode==='register'?'login':'register'">{{loginMode==='register'?t('已有账户','Sign in'):t('注册新账户','Create account')}}</button><button @click="loginMode='reset'">{{t('忘记密码','Forgot password')}}</button><button @click="loginMode=loginMode==='code'?'login':'code'">{{loginMode==='code'?t('密码登录','Password login'):t('验证码登录','Code login')}}</button></div><div class="demo-note"><ShieldCheck :size="18"/><p>{{t('演示账户信息保存在本地 local-only/demo-accounts.json。私有仓库不包含密码。','Demo credentials are in local-only/demo-accounts.json. Passwords are excluded from the repository.')}}</p></div></div></section>
  </div>
  <div v-else class="workspace" :class="{shop:!isAdmin}">
    <aside class="sidebar"><a class="brand" @click="page=isAdmin?'dashboard':'home'"><Sun :size="28"/><b>Luma<span>Supply</span></b></a><div class="workspace-label">{{isAdmin?t('管理工作空间','ADMIN WORKSPACE'):isMerchant?t('商家工作台','SUPPLIER WORKSPACE'):t('我的选灯空间','YOUR LIGHTING SPACE')}}</div><nav><button v-for="n in nav" :key="n.id" :class="{active:page===n.id}" @click="page=n.id"><component :is="n.icon" :size="18"/>{{t(n.zh,n.en)}}<ChevronRight v-if="page===n.id" :size="14"/></button></nav><div class="sidebar-bottom"><div class="status-dot"></div>{{t('本地演示 · 私有项目','LOCAL DEMO · PRIVATE')}}<small>{{t('每一份报价，每一步履约，可追溯。','Every quote. Every delivery. Traceable.')}}</small></div></aside>
    <div class="main-shell"><header class="topbar"><div class="breadcrumb">LumaSupply <ChevronRight :size="14"/> <b>{{currentTitle}}</b></div><div class="top-actions"><button @click="lang=lang==='zh'?'en':'zh'" class="icon-button" aria-label="切换语言"><Languages :size="19"/></button><button @click="page='notifications'" class="icon-button notification" aria-label="消息中心"><Bell :size="19"/><i v-if="unread">{{unread>9?'9+':unread}}</i></button><span class="avatar">{{user.name?.slice(0,1)||'L'}}</span><div class="user-info"><b>{{user.name}}</b><small>{{user.role}}</small></div><button class="icon-button" @click="signout" aria-label="退出登录"><LogOut :size="17"/></button></div></header>
      <main><div v-if="error" role="alert" class="error sticky-error">{{error}}<button @click="error=''">×</button></div>
        <template v-if="page==='home'">
          <div class="shop-hero"><div><span class="eyebrow">THE RIGHT LIGHT, EVERY TIME</span><h1>{{t('找到灵感里的','Find the light')}}<br><em>{{t('那一束光。','you imagined.')}}</em></h1><p>{{t('用图片找到相似灯具，让参数和可靠报价帮您做选择。','Find visual matches. Compare specifications. Source with confidence.')}}</p><div class="hero-tags"><span><ScanLine :size="15"/>{{t('以图搜图','Visual search')}}</span><span><Layers :size="15"/>{{t('多商家报价','Supplier quotes')}}</span><span><ShieldCheck :size="15"/>{{t('平台审核','Reviewed catalog')}}</span></div></div><div class="hero-image"><img :src="mediaUrl('demo-0-0-0')" alt="灯具演示图"/><span class="image-caption">LUMA COLLECTION / 01<br><b>{{t('灯具演示系列','Demo collection')}}</b></span></div></div>
          <section class="search-panel"><div class="search-main"><Search :size="22"/><input v-model="searchText" @keyup.enter="runSearch" :placeholder="t('搜索灯具、SKU，或描述您的灵感…','Search lamps, SKU, or describe your inspiration…')"/><label class="upload-button"><ScanLine :size="18"/>{{t('上传图片','Upload image')}}<input type="file" accept="image/*" @change="fileInput($event,'query','search')"/></label><button class="primary" @click="runSearch" :disabled="busy">{{t('寻找灯具','Find lamps')}}<ArrowUpRight :size="17"/></button></div><div class="filter-row"><SlidersHorizontal :size="16"/><select v-model="category"><option value="">{{t('所有分类','All categories')}}</option><option v-for="c in categories">{{c}}</option></select><label class="inline compact">{{t('预算','Budget')}} ¥<input v-model="maxPrice" type="number" min="0" placeholder="不限"/></label><label class="check"><input v-model="availableOnly" type="checkbox"/>{{t('仅有货','Available only')}}</label><button v-if="searchResult" @click="searchResult=null;searchText='';searchImage=null">{{t('清除搜索','Clear search')}}</button></div><div v-if="searchImage" class="query-preview"><img :src="searchImage.preview" alt="查询图片"/><div><b>{{t('图片已准备好','Image ready')}}</b><label class="check"><input v-model="cropEnabled" type="checkbox"/>{{t('局部选灯：使用归一化目标框','Crop to target: normalized region')}}</label><div v-if="cropEnabled" class="crop-controls"><label v-for="n in ['x','y','w','h']">{{n}}<input type="number" :min="0" :max="1" step="0.05" v-model="crop[n]"/></label></div><small>{{t('x/y 为左上角，w/h 为宽高，范围为 0—1。','x/y: top-left; w/h: width and height, 0–1.')}}</small></div><button @click="searchImage=null">×</button></div></section>
          <div class="section-heading"><div><span class="eyebrow">CURATED FOR YOUR SPACE</span><h2>{{searchResult?t('检索结果','Search results'):t('为每个空间，精选合适的光','A considered light for every space')}}</h2></div><span class="muted">{{shownProducts.length}} {{t('款候选','candidates')}}<template v-if="searchResult"> · {{searchResult.elapsed_ms}} ms</template></span></div>
          <div v-if="searchResult" class="notice">{{searchResult.notice}}<button @click="action(()=>api('/search/'+searchResult.query_id+'/feedback',{issue:'结果不符合需求'}),t('感谢反馈','Feedback saved'))">{{t('反馈结果','Give feedback')}}</button></div>
          <div class="category-pills"><button :class="{active:!category}" @click="category=''">{{t('全部','All')}}</button><button v-for="c in categories" :class="{active:category===c}" @click="category=c">{{c}}</button></div>
          <div class="product-grid"><article v-for="p in shownProducts" :key="p.id+'-'+p.selected_sku_id" class="product-card"><div class="product-photo" @click="openProduct(p)"><img :src="mediaUrl((p.skus.find((s:any)=>s.id===p.selected_sku_id)||p.skus[0]).images[0])" :alt="p.name"/><span class="product-chip">{{p.category}}</span><button class="heart-button" @click.stop="toggleCompare(p.selected_sku_id)" :class="{selected:compareIds.includes(p.selected_sku_id)}" :aria-label="t('加入对比','Compare')"><Plus :size="17"/></button></div><div class="product-copy" @click="openProduct(p)"><small>{{p.skus.find((s:any)=>s.id===p.selected_sku_id)?.code}}</small><h3>{{p.name}}</h3><p>{{p.skus[0].color}} · {{p.skus.length}} {{t('种规格','variants')}}</p><div class="product-bottom"><strong>{{money(p.min_price)}}<small>{{t(' 起',' from')}}</small></strong><span>{{p.quote_count}} {{t('家报价','suppliers')}}</span><ArrowUpRight :size="17"/></div></div></article></div><div v-if="!shownProducts.length" class="empty"><Search :size="40"/><h3>{{t('暂无匹配的灯具','No matching lamps')}}</h3><p>{{t('尝试放宽预算、更换图片或咨询客服。','Try another image, adjust filters or contact support.')}}</p></div>
        </template>
        <template v-else-if="page==='dashboard'"><div class="page-heading"><div><span class="eyebrow">YOUR WORKSPACE, AT A GLANCE</span><h1>{{t('让每一步协同，都有进展。','Every step, moving forward.')}}</h1><p>{{t('审核报价、跟进订单，让合适的灯按时抵达。','Review quotes, follow orders, and keep delivery on track.')}}</p></div><button class="primary" @click="newOrder()"><Plus :size="17"/>{{t('创建销售订单','Create order')}}</button></div><div class="metric-grid"><div class="metric" v-for="[label,value,unit] in [[t('在售商品','Active products'),dashboard.products,t('款','items')],[t('销售订单','Sales orders'),dashboard.orders,t('单','orders')],[t('已确认销售额','Confirmed sales'),money(dashboard.confirmed_sales),''],[t('待审核报价','Pending quotes'),dashboard.pending_quotes,t('项','pending')]]"><span>{{label}}</span><strong>{{value}}<small>{{unit}}</small></strong><div class="metric-rule"></div><small>{{t('来自当前业务数据库','From current business data')}}</small></div></div><div class="dashboard-grid"><section class="panel"><div class="section-heading"><h2>{{t('订单履约进度','Order pipeline')}}</h2><button @click="page='orders'">{{t('查看全部','View all')}} ↗</button></div><div class="pipeline" v-for="(count,status) in dashboard.order_statuses"><span>{{state(String(status))}}</span><div><i :style="{width:Math.max(2,Number(count)/Math.max(1,dashboard.orders)*100)+'%'}"></i></div><b>{{count}}</b></div><div v-if="!dashboard.orders" class="empty-small">{{t('从客户询价创建第一笔订单','Create your first order from an inquiry')}}</div></section><section class="panel dark-panel"><span class="eyebrow">SMARTER SOURCING</span><h2>{{t('最低单价，未必是最低总成本。','Lowest unit price is only part of the story.')}}</h2><p>{{t('采购优化同时考虑供货量、交期与运费。生成建议后，由采购员确认执行。','Optimize availability, lead time and freight. A buyer confirms each proposed plan.')}}</p><button @click="page='procurements'">{{t('进入采购工作台','Open procurement')}}<ArrowUpRight :size="18"/></button></section></div><div class="quick-grid"><button @click="page='tickets'"><MessageSquare/><b>{{dashboard.open_tickets}}</b><span>{{t('待处理售后','Open after-sales')}}</span><ArrowUpRight/></button><button @click="page='index'"><ScanLine/><b>{{dashboard.searches}}</b><span>{{t('累计检索','Searches')}}</span><ArrowUpRight/></button><button @click="page='exceptions'"><ShieldCheck/><b>{{dashboard.no_result_searches}}</b><span>{{t('无结果搜索','No-result searches')}}</span><ArrowUpRight/></button></div></template>
        <template v-else-if="page==='profile'"><div class="page-heading"><div><span class="eyebrow">ACCOUNT & IDENTITY</span><h1>{{currentTitle}}</h1></div><button class="secondary" @click="openModal('password')">{{t('修改密码','Change password')}}</button></div><section class="panel form-panel"><form @submit.prevent="saveProfile"><template v-if="isMerchant"><span class="badge">{{state(form.status)}}</span><p v-if="form.reason">{{form.reason}}</p><label>{{t('店铺名称','Shop name')}}<input v-model="form.shop_name" required/></label><label>{{t('法人姓名','Legal representative')}}<input v-model="form.legal_name" required/></label><label>{{t('联系电话','Phone')}}<input v-model="form.phone" required/></label><label>{{t('商家地址','Address')}}<input v-model="form.address" required/></label><label>{{t('营业执照','Business license')}}<input type="file" accept="image/*" @change="fileInput($event,'license','license_media_id')"/><small>{{form.license_media_id?t('已上传，资料仅审核人员可见','Uploaded; visible only to reviewers'):t('请上传营业执照','Upload a business license')}}</small></label></template><template v-else><label>{{t('用户名','Username')}}<input v-model="form.username" required/></label><label>{{t('显示姓名','Display name')}}<input v-model="form.name" required/></label></template><button class="primary" :disabled="busy">{{isMerchant?t('提交认证审核','Submit verification'):t('保存资料','Save profile')}}</button></form></section><section v-if="!isMerchant" class="panel"><div class="section-heading"><h2>{{t('收货地址','Shipping addresses')}}</h2><button class="secondary" @click="openModal('address')"><Plus :size="16"/>{{t('新增地址','Add address')}}</button></div><div v-for="a in rows" class="list-item"><div><b>{{a.recipient}} · {{a.phone}}</b><p>{{a.detail}}</p></div><button @click="action(async()=>{await api('/addresses/'+a.id,undefined,'DELETE');await load()})">{{t('删除','Delete')}}</button></div><p v-if="!rows.length" class="muted">{{t('暂无地址，也可在订单中选择自提。','No saved addresses. Pickup is also available.')}}</p></section></template>
        <template v-else-if="page==='settings'"><div class="page-heading"><div><span class="eyebrow">BRAND & SERVICE</span><h1>{{currentTitle}}</h1><p>{{t('每组 1—6 项；客服二维码与昵称成对保存。','1–6 entries per group. Each support QR requires a nickname.')}}</p></div><button class="primary" @click="saveSettings">{{t('保存设置','Save settings')}}</button></div><section class="panel" v-for="k in ['customer_banners','merchant_banners','support']"><div class="section-heading"><h2>{{k==='support'?t('客服二维码','Support QR'):k==='customer_banners'?t('客户轮播图','Customer banners'):t('商家轮播图','Merchant banners')}}</h2><button v-if="settings[k]?.length<6" @click="settings[k].push(k==='support'?{image:'',nickname:''}:{image:'',title:'',link:''})">+ {{t('新增','Add')}}</button></div><div v-for="(s,i) in settings[k]" class="setting-row"><img v-if="s.image" :src="mediaUrl(s.image)" alt="运营图片"/><input type="file" accept="image/*" @change="settingUpload($event,k,Number(i))"/><input v-if="k==='support'" v-model="s.nickname" :placeholder="t('客服昵称','Nickname')"/><template v-else><input v-model="s.title" :placeholder="t('标题','Title')"/><input v-model="s.link" placeholder="/product/1"/></template><button v-if="settings[k].length>1" @click="settings[k].splice(i,1)">×</button></div></section></template>
        <template v-else-if="page==='index'"><div class="page-heading"><div><span class="eyebrow">VISUAL RETRIEVAL ENGINE</span><h1>{{currentTitle}}</h1><p>{{dashboard.encoder}} · {{dashboard.images||0}} {{t('张图片','images')}} · {{dashboard.version}}</p></div><button class="primary" @click="action(async()=>{await api('/admin/index/rebuild',{});await load()})"><RefreshCw :size="16"/>{{t('重建索引','Rebuild index')}}</button></div><section class="panel"><div class="list-item" v-for="job in dashboard.tasks"><div><b>#{{job.id}} {{job.reason}}</b><p>{{job.error||job.created_at}}</p></div><span class="badge">{{state(job.status)}}</span><button v-if="job.status==='failed'" @click="action(async()=>{await api('/admin/index/'+job.id+'/retry',{});await load()})">{{t('重试','Retry')}}</button></div></section></template>
        <template v-else-if="page==='notifications'"><div class="page-heading"><h1>{{currentTitle}}</h1></div><section class="panel"><div v-for="n in notifications" class="list-item" :class="{unread:!n.read}"><Bell :size="18"/><div><b>{{n.message}}</b><p>{{n.created_at}}</p></div><button v-if="!n.read" @click="action(async()=>{await api('/notifications/'+n.id+'/read',{});await load()})">{{t('标为已读','Mark read')}}</button></div></section></template>
        <template v-else>
          <div class="page-heading"><div><span class="eyebrow">{{isMerchant?'SUPPLIER COLLABORATION':isAdmin?'OPERATIONS & COLLABORATION':'YOUR LIGHTING JOURNEY'}}</span><h1>{{currentTitle}}</h1><p>{{rows.length}} {{t('条记录 · 数据随业务实时更新','records · live business data')}}</p></div><div class="inline"><button class="icon-button" @click="action(load,'')" aria-label="刷新"><RefreshCw :size="18"/></button><button v-if="page==='orders'&&isAdmin" class="primary" @click="newOrder()"><Plus :size="16"/>{{t('创建订单','Create order')}}</button><button v-if="page==='catalog'" class="primary" @click="openModal('product',{category:categories[0],power_w:18,cct_k:3000})"><Plus :size="16"/>{{t('新建商品','Add product')}}</button><button v-if="page==='users'&&user.role==='admin'" class="primary" @click="openModal('staff',{permissions:[]})">{{t('添加员工','Add staff')}}</button><button v-if="page==='wishlist'&&rows.length" class="primary" @click="makeInquiry">{{t('清单一键询价','Request quote')}}<ArrowUpRight :size="16"/></button></div></div>
          <section v-if="page==='catalog'" class="panel"><div v-for="p in rows" class="catalog-row"><img :src="mediaUrl(p.skus[0]?.images[0])" :alt="p.name"/><div><b>{{p.name}}</b><p>{{p.title}}</p><small>{{p.category}} · {{p.skus.length}} SKU</small></div><span class="badge">{{state(p.status)}}</span><div class="table-actions"><button @click="openModal('edit-product',{...p})">{{t('编辑','Edit')}}</button><template v-if="isAdmin"><button v-if="p.status!=='active'" @click="changeCatalog(p,'active')">{{t('审核上架','Approve')}}</button><button v-else @click="changeCatalog(p,'inactive')">{{t('下架','Unpublish')}}</button><button @click="openModal('sku-price',{id:p.skus[0].id,price:p.skus[0].manual_price===null?'':p.skus[0].manual_price/100,stock_status:p.skus[0].stock_status})">{{t('调价','Pricing')}}</button></template></div></div></section>
          <section v-else-if="page==='wishlist'" class="panel"><div v-for="w in rows" class="catalog-row"><img :src="mediaUrl(w.sku.images[0])" alt="清单商品"/><div><span class="eyebrow">{{w.room}}</span><h3>{{w.product_name}}</h3><p>{{w.sku.code}} · {{w.sku.specification}}</p></div><label class="inline compact">{{t('数量','Qty')}}<input type="number" min="1" v-model="w.quantity" @change="action(()=>api('/wishlist',w))"/></label><strong>{{money(w.sku.price*w.quantity)}}</strong><button @click="action(async()=>{await api('/wishlist/'+w.id,undefined,'DELETE');await load()})">×</button></div></section>
          <section v-else-if="page==='quotes'" class="panel table-panel"><table><thead><tr><th>SKU / {{t('商家','Supplier')}}</th><th>{{t('供货价','Unit price')}}</th><th>{{t('数量 / 交期','Stock / Lead')}}</th><th>{{t('有效期','Valid until')}}</th><th>{{t('状态','Status')}}</th><th>{{t('操作','Actions')}}</th></tr></thead><tbody><tr v-for="q in rows"><td><b>{{q.sku_code}}</b><small>{{q.shop_name}} · v{{q.version}}</small></td><td>{{money(q.price)}}<small>{{t('运费','Freight')}} {{money(q.freight)}}</small></td><td>{{q.available_quantity??t('待确认','Unknown')}} / {{q.lead_days}} {{t('天','days')}}</td><td>{{q.valid_until.slice(0,10)}}</td><td><span class="badge" :class="q.status">{{state(q.status)}}{{!q.active?' · '+t('下架','inactive'):''}}</span><small>{{q.reason}}</small></td><td class="table-actions"><template v-if="isAdmin&&q.status==='pending'"><button @click="review('/quotes',q.id,true)">{{t('通过','Approve')}}</button><button @click="review('/quotes',q.id,false)">{{t('驳回','Reject')}}</button></template><template v-if="isMerchant&&!q.deleted"><button @click="openModal('quote',{...q,sku_code:q.sku_code,price:q.price/100,freight:q.freight/100,valid_until:q.valid_until.slice(0,10)})">{{t('新版本报价','Revise')}}</button><button v-if="q.active" @click="action(async()=>{await api('/quotes/'+q.id+'/action',{action:'withdraw'});await load()})">{{t('下架','Withdraw')}}</button><button v-else @click="action(async()=>{await api('/quotes/'+q.id+'/action',{action:'resubmit'});await load()})">{{t('重新提交','Resubmit')}}</button></template></td></tr></tbody></table></section>
          <section v-else-if="page==='orders'" class="panel table-panel"><table><thead><tr><th>{{t('订单','Order')}}</th><th>{{t('客户 / 客服','Customer / Service')}}</th><th>{{t('金额','Amount')}}</th><th>{{t('销售状态','Order status')}}</th><th>{{t('采购 / 发货','Procurement / Shipping')}}</th><th></th></tr></thead><tbody><tr v-for="o in rows"><td><b>{{o.number}}</b><small>{{o.created_at.slice(0,16).replace('T',' ')}}</small></td><td>{{o.customer_name}}<small>{{o.service_name}}</small></td><td>{{money(o.total)}}</td><td><span class="badge">{{state(o.status)}}</span></td><td>{{state(o.procurement_status)}}<small>{{state(o.shipment_status)}}</small></td><td><button @click="openOrder(o)">{{t('查看详情','Details')}} ↗</button></td></tr></tbody></table></section>
          <section v-else-if="page==='procurements'" class="panel"><div v-for="p in rows" class="procurement-card"><div class="section-heading"><div><span class="eyebrow">{{p.order_number}}</span><h3>{{t('采购记录','Procurement')}} #{{p.id}}</h3></div><span class="badge">{{state(p.status)}}</span></div><div v-if="p.plan" class="plan-summary"><span>{{t('求解状态','Solver')}}<b>{{p.plan.status}}</b></span><span>{{t('总成本','Total cost')}}<b>{{p.plan.total_cost!==undefined?money(p.plan.total_cost):'—'}}</b></span><span>{{t('供货商','Suppliers')}}<b>{{p.plan.supplier_count??'—'}}</b></span><span>{{t('交期','Lead time')}}<b>{{p.plan.lead_days??'—'}} {{t('天','days')}}</b></span></div><p v-if="p.plan?.reasons" class="muted">{{p.plan.reasons.map((r:any)=>r.reason).join('；')}}</p><div class="table-actions"><button v-if="['draft','planned','exception'].includes(p.status)" class="secondary" @click="openModal('plan-config',{...p,max_days:30})"><SlidersHorizontal :size="15"/>{{t('生成采购方案','Generate plan')}}</button><button v-if="p.status==='planned'" class="primary" @click="openModal('plan-result',{...p})">{{t('查看并确认','Review plan')}}</button><button v-if="p.status==='processing'" class="primary" @click="openModal('proof',{order_id:p.order_id})">{{t('上传采购凭证','Complete procurement')}}</button></div></div></section>
          <section v-else-if="page==='inquiries'" class="panel"><div v-for="r in rows" class="list-item"><div><span class="eyebrow">INQUIRY #{{r.id}}</span><h3>{{r.items.length}} {{t('个选购条目','selected items')}}</h3><p>{{r.message||t('客户房间清单询价','Room list inquiry')}}</p><small>{{r.items.map((i:any)=>'SKU '+i.sku_id+' × '+i.quantity+' / '+i.room).join(' · ')}}</small></div><span class="badge">{{state(r.status)}}</span><button v-if="isAdmin&&r.status==='open'" class="primary" @click="newOrder(r)">{{t('转为销售订单','Create order')}}</button></div></section>
          <section v-else-if="page==='merchants'" class="panel"><div v-for="m in rows" class="list-item"><div><h3>{{m.shop_name}}</h3><p>{{m.legal_name}} · {{m.phone}}</p><small>{{m.address}}</small><button v-if="m.license_media_id" @click="privateMedia(m.license_media_id)">{{t('查看营业执照','View license')}}</button></div><span class="badge">{{state(m.status)}}</span><div class="table-actions"><template v-if="m.status==='pending'"><button @click="review('/admin/merchants',m.id,true)">{{t('通过','Approve')}}</button><button @click="review('/admin/merchants',m.id,false)">{{t('驳回','Reject')}}</button></template><button v-if="m.status!=='disabled'" @click="action(async()=>{await api('/admin/merchants/'+m.id+'/disable',{});await load()})">{{t('禁用','Disable')}}</button></div></div></section>
          <section v-else-if="page==='users'" class="panel table-panel"><table><thead><tr><th>ID</th><th>{{t('账户','Account')}}</th><th>{{t('姓名','Name')}}</th><th>{{t('角色','Role')}}</th><th>{{t('模块权限','Permissions')}}</th><th>{{t('状态','Status')}}</th></tr></thead><tbody><tr v-for="u in rows"><td>{{u.id}}</td><td>{{u.username}}</td><td>{{u.name}}</td><td>{{u.role}}</td><td>{{u.permissions.join(', ')||'—'}}</td><td>{{u.active?t('启用','Active'):t('禁用','Disabled')}}</td></tr></tbody></table></section>
          <section v-else-if="page==='tickets'" class="panel"><div v-for="r in rows" class="list-item"><div><h3>#{{r.id}} · {{r.category}} · {{t('订单','Order')}} #{{r.order_id}}</h3><p>{{r.description}}</p><small>{{r.history.map((h:any)=>h.by+': '+h.note).join(' → ')}}</small></div><span class="badge">{{state(r.status)}}</span><button v-if="isAdmin&&r.status!=='closed'" @click="openModal('ticket-update',{...r,status:r.status==='open'?'processing':r.status==='resolved'?'closed':'resolved',note:''})">{{t('处理','Process')}}</button><button v-if="!isAdmin&&r.status==='need_information'" @click="openModal('ticket-supplement',{id:r.id})">{{t('补充资料','Add information')}}</button></div></section>
          <section v-else-if="page==='reviews'" class="panel"><div v-for="r in rows" class="list-item"><div><span class="eyebrow">SKU #{{r.sku_id}}</span><p>{{r.text}}</p><small>{{r.reply}}</small><div class="media-strip"><template v-for="m in r.media_ids"><a :href="mediaUrl(m)" target="_blank">{{t('查看附件','View attachment')}}</a></template></div></div><button @click="openModal('reply',{id:r.id,reply:r.reply,deleted:false})">{{t('回复 / 管理','Reply / Moderate')}}</button></div></section>
          <section v-else-if="page==='audits'" class="panel table-panel"><table><thead><tr><th>{{t('时间','Time')}}</th><th>{{t('操作人','Actor')}}</th><th>{{t('动作','Action')}}</th><th>{{t('对象','Target')}}</th></tr></thead><tbody><tr v-for="r in rows"><td>{{r.created_at}}</td><td>{{r.user_id}}</td><td>{{r.action}}</td><td>{{r.target}}</td></tr></tbody></table></section>
          <section v-else-if="page==='exceptions'" class="panel"><div v-for="r in rows" class="list-item"><ShieldCheck/><div><h3>{{r.message}}</h3><p>{{r.owner}} · {{r.created_at}}</p></div><span class="badge">{{state(r.status)}}</span></div></section>
          <div v-if="!rows.length" class="empty"><Package :size="38"/><h3>{{t('这里暂时没有记录','No records yet')}}</h3><p>{{t('完成上游业务后，记录会出现在这里。','Records appear here as your workflow progresses.')}}</p></div>
        </template>
        <footer><span>LumaSupply / {{t('灯具供应协同平台','Lighting supply collaboration')}}</span><span>{{t('课程演示 · 金额以人民币展示','Course demo · Prices in CNY')}}</span></footer>
      </main>
    </div>
  </div>
  <div v-if="compareIds.length&&user" class="compare-bar"><Layers :size="18"/><b>{{compareIds.length}} {{t('款规格待对比','variants selected')}}</b><button @click="compareOpen=true">{{t('开始对比','Compare now')}} ↗</button><button @click="compareIds=[]">×</button></div>
  <div v-if="toast" class="toast"><Check :size="18"/>{{toast}}</div>

  <div v-if="selected" class="overlay" @click.self="selected=null"><section class="dialog product-dialog"><button class="close" @click="selected=null" aria-label="关闭"><X/></button><div class="detail-photo"><img :src="mediaUrl(activeSku?.images[0])" :alt="selected.name" @click="window.open(mediaUrl(activeSku?.images[0]),'_blank')"/><small>{{t('点击查看规格原图','Click to view original image')}}</small></div><div class="detail-copy"><span class="eyebrow">{{selected.category}} / {{activeSku?.code}}</span><h2>{{selected.name}}</h2><p class="muted">{{selected.description}}</p><strong class="detail-price">{{money(activeSku?.price)}} <small>{{state(activeSku?.stock_status)}}</small></strong><label>{{t('选择具体规格','Select a variant')}}<select v-model="skuId"><option v-for="s in selected.skus" :value="s.id">{{s.code}} · {{s.color}} · {{s.specification}}</option></select></label><dl class="spec-grid"><template v-for="(value,k) in activeSku?.attributes"><dt>{{k}}</dt><dd>{{value??t('待补充','Not provided')}}</dd></template><dt>{{t('尺寸 mm','Size mm')}}</dt><dd>{{activeSku?.size_mm||t('待补充','Not provided')}}</dd></dl><div class="inline"><button class="secondary" @click="toggleCompare(skuId)"><Plus :size="16"/>{{t('加入对比','Compare')}}</button><button class="secondary" @click="shareSku">{{t('分享规格','Share variant')}}</button></div><template v-if="user?.role==='customer'"><label>{{t('加入哪个房间','Room')}}<input v-model="form.room" :placeholder="t('客厅','Living room')"/></label><button class="primary full" @click="saveWish"><Heart :size="17"/>{{t('加入选购清单','Add to room list')}}</button></template><button v-if="isMerchant" class="primary full" @click="quoteForm(activeSku)">{{t('我要报价','Submit a quote')}}</button><div class="support-box"><MessageSquare :size="18"/><div><b>{{t('联系客服购买 · 批发与定制面议','Contact service · Wholesale and custom orders')}}</b><div v-for="s in settings.support" class="inline"><img :src="mediaUrl(s.image)" alt="客服二维码"/><small>{{s.nickname}}</small></div></div></div><div v-for="r in modalRows" class="review"><p>{{r.text}}</p><small>{{r.reply}}</small></div></div></section></div>
  <div v-if="compareOpen" class="overlay" @click.self="compareOpen=false"><section class="dialog wide"><button class="close" @click="compareOpen=false"><X/></button><h2>{{t('规格对比','Compare specifications')}}</h2><table><thead><tr><th>{{t('参数','Parameter')}}</th><th v-for="s in compareSkus">{{s.product_name}}<small>{{s.code}}</small></th></tr></thead><tbody><tr><th>{{t('价格','Price')}}</th><td v-for="s in compareSkus">{{money(s.price)}}</td></tr><tr v-for="k in ['size_mm','color','specification']"><th>{{k}}</th><td v-for="s in compareSkus">{{s[k]||t('待补充','Not provided')}}</td></tr><tr v-for="k in ['power_w','cct_k','voltage_v','material']"><th>{{k}}</th><td v-for="s in compareSkus">{{s.attributes[k]??t('待补充','Not provided')}}</td></tr></tbody></table></section></div>
  <div v-if="modal" class="overlay" @click.self="modal=''">
    <section class="dialog" :class="{wide:['order-detail','new-order','plan-result','product'].includes(modal)}"><button class="close" @click="modal=''" aria-label="关闭"><X/></button><div v-if="error" class="error">{{error}}</div>
      <form v-if="modal==='quote'" @submit.prevent="saveQuote"><span class="eyebrow">SUPPLIER OFFER / {{form.sku_code}}</span><h2>{{t('提交供货报价','Submit supplier offer')}}</h2><p class="muted">{{t('每次提交生成新版本，通过审核后生效。','Every submission creates a new version, effective after approval.')}}</p><div class="form-grid"><label>{{t('供货单价 元','Unit price CNY')}}<input v-model="form.price" type="number" min="0.01" step="0.01" required/></label><label>{{t('可供数量 留空为待确认','Available quantity')}}<input v-model="form.available_quantity" type="number" min="0"/></label><label>{{t('起订量','Minimum quantity')}}<input v-model="form.min_quantity" type="number" min="1" required/></label><label>{{t('交期 天','Lead days')}}<input v-model="form.lead_days" type="number" min="0" required/></label><label>{{t('运费 元','Freight CNY')}}<input v-model="form.freight" type="number" min="0" step="0.01" required/></label><label>{{t('有效期','Valid until')}}<input v-model="form.valid_until" type="date" required/></label></div><button class="primary full" :disabled="busy">{{t('提交审核','Submit for approval')}}</button></form>
      <form v-else-if="modal==='reject'" @submit.prevent="reject"><h2>{{t('填写驳回原因','Rejection reason')}}</h2><label>{{t('让商家知道需要修改什么','Explain what needs changing')}}<textarea v-model="form.reason" required></textarea></label><button class="primary">{{t('确认驳回','Reject')}}</button></form>
      <form v-else-if="modal==='address'" @submit.prevent="saveAddress"><h2>{{t('新增收货地址','New address')}}</h2><label>{{t('收件人','Recipient')}}<input v-model="form.recipient" required/></label><label>{{t('联系电话','Phone')}}<input v-model="form.phone" required/></label><label>{{t('详细地址','Address')}}<textarea v-model="form.detail" required></textarea></label><button class="primary">{{t('保存地址','Save address')}}</button></form>
      <form v-else-if="modal==='product'" @submit.prevent="saveProduct"><h2>{{t('新建商品与首个规格','Create product and first variant')}}</h2><div class="form-grid"><label>{{t('商品名称','Name')}}<input v-model="form.name" required/></label><label>{{t('搜索标题','Search title')}}<input v-model="form.title" required/></label><label>{{t('分类','Category')}}<select v-model="form.category"><option v-for="c in categories">{{c}}</option></select></label><label>SKU<input v-model="form.code" required/></label><label>{{t('颜色','Color')}}<input v-model="form.color"/></label><label>{{t('尺寸 mm','Size mm')}}<input v-model="form.size_mm"/></label><label>{{t('规格说明','Specification')}}<input v-model="form.specification"/></label><label>{{t('初始价格 元','Initial price CNY')}}<input type="number" min="0" step="0.01" v-model="form.price" required/></label><label>{{t('功率 W','Power W')}}<input type="number" min="0" v-model="form.power_w" required/></label><label>{{t('色温 K','CCT K')}}<input type="number" min="0" v-model="form.cct_k" required/></label></div><label>{{t('商品说明','Description')}}<textarea v-model="form.description"></textarea></label><label>{{t('商品图片','Product image')}}<input type="file" accept="image/*" @change="fileInput($event,'product','image')" required/></label><button class="primary" :disabled="busy">{{isMerchant?t('提交审核','Submit for approval'):t('发布商品','Publish')}}</button></form>
      <form v-else-if="modal==='new-order'" @submit.prevent="saveOrder"><h2>{{t('创建销售订单','Create sales order')}}</h2><label>{{t('客户','Customer')}}<select v-model="form.customer_id" required><option value="">{{t('请选择客户','Select customer')}}</option><option v-for="u in modalRows" :value="u.id">{{u.name}} / {{u.username}}</option></select></label><div v-for="(item,i) in form.items" class="order-entry"><label>SKU<select v-model="item.sku_id" required><option value="">{{t('选择规格','Select variant')}}</option><optgroup v-for="p in catalog" :label="p.name"><option v-for="s in p.skus" :value="s.id">{{s.code}} {{s.specification}} {{money(s.price)}}</option></optgroup></select></label><label>{{t('数量','Quantity')}}<input v-model="item.quantity" type="number" min="1" required/></label><label>{{t('成交单价 留空使用展示价','Final price CNY (optional)')}}<input v-model="item.unit_price" type="number" min="0" step="0.01"/></label><button v-if="form.items.length>1" type="button" @click="form.items.splice(i,1)">×</button></div><button type="button" class="secondary" @click="form.items.push({sku_id:'',quantity:1,unit_price:''})">+ {{t('添加规格','Add variant')}}</button><label>{{t('备注','Notes')}}<textarea v-model="form.remark"></textarea></label><button class="primary full" :disabled="busy">{{t('创建订单并通知客户','Create and notify customer')}}</button></form>
      <template v-else-if="modal==='order-detail'"><span class="eyebrow">{{detailOrder.number}}</span><h2>{{t('订单详情','Order details')}}</h2><div class="inline"><span class="badge">{{state(detailOrder.status)}}</span><strong>{{money(detailOrder.total)}}</strong><span>{{detailOrder.customer_name}} / {{detailOrder.service_name}}</span></div><table><thead><tr><th>SKU</th><th>{{t('数量','Qty')}}</th><th>{{t('单价','Unit price')}}</th><th>{{t('已发','Shipped')}}</th></tr></thead><tbody><tr v-for="l in detailOrder.lines"><td>{{l.snapshot.product_name}}<small>{{l.snapshot.code}} · {{l.snapshot.specification}}</small></td><td>{{l.quantity}}</td><td>{{money(l.unit_price)}}</td><td>{{l.shipped_quantity}}</td></tr></tbody></table><p>{{detailOrder.remark}}</p><p v-if="detailOrder.address_snapshot">{{detailOrder.address_snapshot.recipient}} / {{detailOrder.address_snapshot.phone}} / {{detailOrder.address_snapshot.detail}}</p><p v-else-if="detailOrder.delivery_mode==='pickup'">{{t('客户自提','Customer pickup')}}</p><div v-for="s in detailOrder.shipments" class="notice">{{s.carrier}} {{s.tracking||t('自提凭证','Pickup receipt')}}<button v-for="m in s.proof_media_ids" @click="privateMedia(m)">{{t('查看凭证','View proof')}}</button></div><template v-if="user.role==='customer'&&detailOrder.status==='awaiting_confirmation'"><label>{{t('取货方式','Fulfillment')}}<select v-model="form.delivery_mode"><option value="pickup">{{t('自提','Pickup')}}</option><option value="delivery">{{t('配送','Delivery')}}</option></select></label><label v-if="form.delivery_mode==='delivery'">{{t('收货地址','Address')}}<select v-model="form.address_id"><option v-for="a in modalRows" :value="a.id">{{a.recipient}} {{a.detail}}</option></select></label><button class="primary" @click="confirmOrder">{{t('确认订单','Confirm order')}}</button></template><div class="table-actions"><button v-if="['awaiting_confirmation','confirmed'].includes(detailOrder.status)" @click="action(async()=>{await api('/orders/'+detailOrder.id+'/cancel',{version:detailOrder.version});modal='';await load()})">{{t('取消订单','Cancel order')}}</button><button v-if="isAdmin&&detailOrder.status==='fulfilling'" class="primary" @click="openModal('shipment',{})">{{t('创建发货记录','Record shipment')}}</button><button v-if="user.role==='customer'&&detailOrder.status==='fulfilling'" class="primary" @click="receiveOrder(detailOrder)">{{t('确认全部签收','Confirm receipt')}}</button><button v-if="user.role==='customer'&&['fulfilling','completed'].includes(detailOrder.status)" @click="openModal('ticket',{line_id:detailOrder.lines[0].id,quantity:1,category:'damaged'})">{{t('申请售后','Request after-sales')}}</button><button v-if="user.role==='customer'&&detailOrder.status==='completed'" @click="openModal('review',{sku_id:detailOrder.lines[0].sku_id})">{{t('评价商品','Review product')}}</button></div></template>
      <form v-else-if="modal==='plan-config'" @submit.prevent="plan(form)"><h2>{{t('采购方案约束','Procurement constraints')}}</h2><label>{{t('最长交期 天','Maximum lead days')}}<input type="number" min="0" max="365" v-model="form.max_days" required/></label><label>{{t('最多供应商 留空不限','Maximum suppliers (optional)')}}<input type="number" min="1" v-model="form.max_suppliers"/></label><label>{{t('预算上限 元 留空不限','Budget CNY (optional)')}}<input type="number" min="0" v-model="form.budget"/></label><p class="muted">{{t('同一 SKU 不拆单，运费按每个商家的最高适用运费收取一次。未知库存不参与求解。','One supplier per SKU. Each supplier charges the maximum applicable freight once. Unknown stock is excluded.')}}</p><button class="primary full" :disabled="busy">{{t('计算方案','Generate plan')}}</button></form>
      <template v-else-if="modal==='plan-result'"><span class="eyebrow">PROCUREMENT OPTIMIZATION</span><h2>{{t('采购方案建议','Proposed procurement plan')}}</h2><span class="badge">{{form.plan.status}}</span><div v-if="form.plan.total_cost!==undefined" class="plan-summary"><span>{{t('方案总成本','Proposed cost')}}<b>{{money(form.plan.total_cost)}}</b></span><span>{{t('逐项最低单价基线','Unit-price baseline')}}<b>{{money(form.plan.baselines?.unit_price?.total_cost)}}</b></span><span>{{t('供应商数量','Suppliers')}}<b>{{form.plan.supplier_count}}</b></span></div><table v-if="form.plan.allocation"><thead><tr><th>SKU</th><th>{{t('商家','Supplier')}}</th><th>{{t('数量','Qty')}}</th><th>{{t('货品成本','Goods cost')}}</th><th>{{t('交期','Lead days')}}</th></tr></thead><tbody><tr v-for="a in form.plan.allocation"><td>{{a.sku_id}}</td><td>#{{a.merchant_id}}</td><td>{{a.quantity}}</td><td>{{money(a.goods_cost)}}</td><td>{{a.lead_days}}</td></tr></tbody></table><p v-for="r in form.plan.reasons">{{r.reason}}</p><p class="muted">{{t('确认时再次校验报价版本、有效期、商家状态和库存。','Quote version, expiry, merchant status and inventory are checked again at confirmation.')}}</p><button v-if="form.status==='planned'" class="primary full" @click="confirmPlan(form)" :disabled="busy">{{t('确认采购并预留数量','Confirm and reserve stock')}}</button></template>
      <form v-else-if="modal==='proof'" @submit.prevent="completeProcurement"><h2>{{t('完成采购','Complete procurement')}}</h2><label>{{t('采购凭证图片','Procurement receipt')}}<input type="file" accept="image/*" @change="fileInput($event,'proof','proof')" required/></label><button class="primary" :disabled="!form.proof||busy">{{t('确认完成','Complete')}}</button></form>
      <form v-else-if="modal==='shipment'" @submit.prevent="shipOrder"><h2>{{t('登记发货或自提','Record shipping or pickup')}}</h2><label>{{t('承运商','Carrier')}}<input v-model="form.carrier"/></label><label>{{t('快递单号 配送必填','Tracking (required for delivery)')}}<input v-model="form.tracking" :required="detailOrder.delivery_mode==='delivery'"/></label><label v-for="l in detailOrder.lines">{{l.snapshot.code}} ({{t('待发','Remaining')}} {{l.quantity-l.shipped_quantity}})<input v-model="form['qty_'+l.id]" type="number" min="0" :max="l.quantity-l.shipped_quantity"/></label><label>{{t('发货凭证','Shipping proof')}}<input type="file" accept="image/*" @change="fileInput($event,'proof','proof')" required/></label><button class="primary" :disabled="!form.proof||busy">{{t('保存发货记录','Save shipment')}}</button></form>
      <form v-else-if="modal==='ticket'" @submit.prevent="saveTicket"><h2>{{t('申请售后','After-sales request')}}</h2><label>{{t('订单商品','Order item')}}<select v-model="form.line_id"><option v-for="l in detailOrder.lines" :value="l.id">{{l.snapshot.code}}</option></select></label><label>{{t('数量','Quantity')}}<input v-model="form.quantity" type="number" min="1" required/></label><label>{{t('问题类型','Issue')}}<select v-model="form.category"><option value="damaged">{{t('破损','Damaged')}}</option><option value="missing">{{t('缺件','Missing')}}</option><option value="wrong">{{t('错发','Wrong item')}}</option><option value="other">{{t('其他','Other')}}</option></select></label><label>{{t('问题说明','Description')}}<textarea v-model="form.description" required></textarea></label><label>{{t('图片或视频','Image or video')}}<input type="file" accept="image/*,video/mp4" @change="fileInput($event,'ticket','attachment')"/></label><button class="primary">{{t('提交申请','Submit')}}</button></form>
      <form v-else-if="modal==='review'" @submit.prevent="saveReview"><h2>{{t('商品评价','Product review')}}</h2><label>SKU<select v-model="form.sku_id"><option v-for="l in detailOrder.lines" :value="l.sku_id">{{l.snapshot.code}}</option></select></label><label>{{t('使用体验','Your experience')}}<textarea v-model="form.text" required></textarea></label><label>{{t('图片或视频','Image or video')}}<input type="file" accept="image/*,video/mp4" @change="fileInput($event,'review','attachment')"/></label><button class="primary">{{t('发布评价','Publish review')}}</button></form>
      <form v-else @submit.prevent="submitGeneric"><h2>{{({staff:t('添加员工','Add staff'),reply:t('回复与管理评价','Review moderation'),'ticket-update':t('处理售后','Process ticket'),'ticket-supplement':t('补充资料','Add information'),password:t('修改密码','Change password'),'sku-price':t('SKU 价格与供货状态','SKU price and availability'),'edit-product':t('修改商品资料','Edit product')})[modal]}}</h2>
      <template v-if="modal==='staff'"><label>{{t('用户名','Username')}}<input v-model="form.username" required/></label><label>{{t('姓名','Name')}}<input v-model="form.name" required/></label><label>{{t('初始密码','Initial password')}}<input v-model="form.password" type="password" minlength="8" required/></label><div class="permission-grid"><label v-for="m in ['users','merchants','catalog','quotes','orders','procurement','operations','reports']" class="check"><input v-model="form.permissions" type="checkbox" :value="m"/>{{m}}</label></div></template>
      <template v-if="modal==='reply'"><label>{{t('回复','Reply')}}<textarea v-model="form.reply"></textarea></label><label class="check"><input v-model="form.deleted" type="checkbox"/>{{t('删除此评价','Delete review')}}</label></template>
      <template v-if="modal==='ticket-update'"><label>{{t('处理状态','Status')}}<select v-model="form.status"><option v-for="s in ['processing','need_information','resolved','closed']" :value="s">{{state(s)}}</option></select></label><label>{{t('处理记录','Note')}}<textarea v-model="form.note" required></textarea></label></template>
      <template v-if="modal==='ticket-supplement'"><label>{{t('补充说明','Additional information')}}<textarea v-model="form.note" required></textarea></label><input type="file" accept="image/*,video/mp4" @change="fileInput($event,'ticket','attachment')"/></template>
      <template v-if="modal==='password'"><label>{{t('原密码','Current password')}}<input v-model="form.old_password" type="password" required/></label><label>{{t('新密码','New password')}}<input v-model="form.new_password" type="password" minlength="8" required/></label></template>
      <template v-if="modal==='sku-price'"><label>{{t('人工最终价 元 留空恢复规则','Manual final price CNY (blank uses rule)')}}<input v-model="form.price" type="number" min="0" step="0.01"/></label><label>{{t('供货状态','Stock status')}}<select v-model="form.stock_status"><option v-for="s in ['available','unavailable','unconfirmed']" :value="s">{{state(s)}}</option></select></label></template>
      <template v-if="modal==='edit-product'"><label>{{t('名称','Name')}}<input v-model="form.name" required/></label><label>{{t('标题','Title')}}<input v-model="form.title" required/></label><label>{{t('分类','Category')}}<input v-model="form.category" required/></label><label>{{t('商品说明','Description')}}<textarea v-model="form.description"></textarea></label></template><button class="primary full" :disabled="busy">{{t('保存','Save')}}</button></form>
    </section>
  </div>
</template>
